export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";

export const METRIC_SELECTION_CHANGE = "EVENT/METRIC_SELECTION_CHANGE";

export const MULTIPLE_MEASUREMENTS_RECEIVED = "EVENT/MULTIPLE_MEASUREMENTS_RECEIVED";
export const MULTIPLE_MEASUREMENTS_ERROR = "EVENT/MULTIPLE_MEASUREMENTS_ERROR_RECEIVED";

export const NEW_MEASUREMENTS_RECEIVED = "EVENT/NEW_MEASUREMENTS_RECEIVED";
export const NEW_MEASUREMENTS_ERROR = "EVENT/NEW_MEASUREMENTS_ERROR_RECEIVED";
